from logging import DEBUG

SERVER_NOISE_PORT = 5555
SERVER_FRONTEND_PORT = 8080
SERVER_LISTEN_IP = "0.0.0.0"
SERVER_DATA_PATH = "./data/"
SERVER_CLIENTS_FILENAME = "clients.json"
SERVER_MESSAGES_FILENAME = "messages.json"
SERVER_LOG_LEVEL = DEBUG
SERVER_SSL_POLICY = "adhoc"
ENCODING = "UTF-8"
SOCK_BUFFER = 4096
SERVER_PRIVATE_KEY_PASS = b"testpassword"

CLIENT_DATA_PATH = "./client"
CLIENT_DATA = "client.data"
CLIENT_PRIVATE_KEY_PASS = b"testpassword"
