from logging import DEBUG

SERVER_PORT = 5555
SERVER_LISTEN_IP = "0.0.0.0"
SERVER_DATA_PATH = "./data/"
SERVER_CLIENTS_FILENAME = "clients.json"
SERVER_MESSAGES_FILENAME = "messages.json"
SERVER_LOG_LEVEL = DEBUG
SERVER_SSL_POLICY = "adhoc"

SOCK_BUFFER = 4096
