# This is a basic workflow to help you get started with Actions
name: Black code formatter

# Controls when the action will run.
# Triggers the workflow on push request event
on: push

jobs:
  # This workflow contains a single job called "build"
  black:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: psf/black@stable
        with:
          args: "*.py --check --line-length 120"
